Repository NeeGongNaeGong/android, pull requests merged in 2025-07, with the labels that each got.

#167 권한별 Drawer 메뉴 관련 로직 처리
  .husky/pre-commit
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkStudyGroupDataSource.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkStudyGroupDataSourceImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/mapper/studygroup/MyStudyGroupListMapper.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/mapper/studygroup/StudyGroupDetailMapper.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/studygroup/response/MyStudyGroupListResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/studygroup/response/StudyGroupDetailResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/paging/MyStudyGroupListPagingSource.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/remote/StudyGroupApi.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/repository/StudyGroupRepositoryImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studygroup/MyStudyGroupInfo.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studygroup/StudyGroupDetailInfo.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/repository/StudyGroupRepository.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/usecase/studygroup/GetMyStudyListUseCase.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/usecase/studygroup/GetStudyDetailUseCase.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/MainScreen.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/StudiesImagePicker.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/drawer/StudiesDrawer.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/drawer/component/PagingItem.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/drawer/model/Role.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/StudiesDetailScreen.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/StudiesDetailViewModel.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/edit/StudiesEditScreen.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/join/StudiesWaitingToJoinScreen.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/join/component/StudiesApplicationJoinUnit.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/role/StudiesMemberRoleScreen.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/role/component/StudiesMemberRoleUnit.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/navigation/AppNavigation.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/navigation/StudiesNavGraph.kt
Labels: 💡Feature

#165 스터디 상세화면 : 최근 공지, 투표 미리보기 및 탭 이동
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkStudiesDataSource.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkStudiesDataSourceImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/mapper/studies/StudiesContentsMapper.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/studies/response/GetStudiesLatestContentResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/studies/response/GetStudiesLatestContentsReadStatusResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/studies/response/StudiesLatestContentResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/remote/StudiesApi.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/repository/StudiesRepositoryImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studies/NotificationData.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studies/StudiesLatestContent.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studies/StudiesLatestContents.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studies/StudiesLatestContentsReadStatus.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studies/combination/StudiesContentsWithReadStatus.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/repository/StudiesRepository.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/usecase/studies/GetStudiesLatestContentsUseCase.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/usecase/studies/PatchStudiesLatestContentsReadStatusUseCase.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/detail/NotificationWindow.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/detail/section/NotificationsSection.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/detail/section/ProfilesSection.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/StudiesDetailContract.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/StudiesDetailScreen.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/StudiesDetailViewModel.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/component/StudiesDetailKebabMenu.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/navigation/StudiesNavGraph.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/util/DateUtils.kt
  app/src/main/res/drawable/ic_studies_detail_announcement.xml
  app/src/main/res/drawable/ic_studies_detail_notice.xml
  app/src/main/res/drawable/ic_studies_detail_voting.xml
  app/src/main/res/drawable/ic_topbar_menu_burger.xml
  app/src/main/res/drawable/ic_topbar_menu_kebab.xml
Labels: 💡Feature, 🎨UI

#166 스터디 상세화면 : 피드에 작성자 추가
  app/src/main/java/com/ssafy/neegongnaegong/data/mapper/learningrecord/LearningRecordMapper.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/learningrecord/response/AuthorResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/learningrecord/response/GetLearningRecordResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/learning/LearningRecord.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/preview/personal/PersonalPreviewDataProvider.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studygroup/StudyContentInfo.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/component/TopAppBar.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/component/studyrecord/StudyRecordItem.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/component/studyrecord/StudyRecordList.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/StudiesDetailScreen.kt
Labels: 💡Feature, 💪Refactor, 🎨UI

#172 내 스터디 목록 조회
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/StudiesContract.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/StudiesScreen.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/StudiesViewModel.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/StudiesCard.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/StudiesWindow.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/dialog/StudiesInfoDialog.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/StudiesDetailViewModel.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/find/StudiesFindContract.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/find/StudiesFindScreen.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/find/StudiesFindViewModel.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/navigation/AppNavigation.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/navigation/StudiesNavGraph.kt
Labels: 💡Feature, 🎨UI

#174 앱 이름 및 로고 변경
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/img_app_main_logo.png
  app/src/main/res/drawable/img_main_character.png
  app/src/main/res/values/strings.xml
Labels: 💪Refactor

#182 그룹 이미지 로딩 실패 시 기본 이미지로 수정
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/StudiesWindow.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/drawer/StudiesDrawer.kt
Labels: 🎨UI

#184 그룹 삭제 로직 추가
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/drawer/StudiesDrawer.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/StudiesDetailContract.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/StudiesDetailScreen.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/StudiesDetailViewModel.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/navigation/MainNavigationGraph.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/navigation/StudiesNavGraph.kt
Labels: 🎨UI, 🚨Bug

#185 스터디 생성시 이미지 업로드 로직 변경
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkStudiesDataSource.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkStudiesDataSourceImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/studies/request/CreateStudiesRequest.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/studies/request/PatchStudiesProfileImage.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/remote/StudiesApi.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/repository/StudiesRepositoryImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/repository/StudiesRepository.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/usecase/file/IssuePresignedUrlUseCase.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/usecase/studies/CreateStudiesUseCase.kt
  app/src/main/java/com/ssafy/neegongnaegong/module/di/usecase/StudiesUseCaseModule.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/create/StudiesCreateContract.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/create/StudiesCreateScreen.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/create/StudiesCreateViewModel.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/edit/StudiesEditViewModel.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/navigation/StudiesNavGraph.kt
Labels: 💡Feature

#201 공부기록 삭제
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkLearningRecordDataSource.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkLearningRecordDataSourceImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/remote/LearningRecordApi.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/repository/LearningRecordRepositoryImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/repository/LearningRecordRepository.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/usecase/learningrecord/DeleteLearningRecordUseCase.kt
  app/src/main/java/com/ssafy/neegongnaegong/module/di/usecase/LearningRecordUseCaseModule.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/personal/edit/StudyRecordEditContract.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/personal/edit/StudyRecordEditScreen.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/personal/edit/StudyRecordEditViewModel.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/timer/component/write/DateTimeHeader.kt
  app/src/main/res/drawable/ic_common_trash.xml
Labels: 💡Feature

#205 공부 기록 태그 삭제 버그 해결
  app/src/main/java/com/ssafy/neegongnaegong/presentation/personal/edit/StudyRecordEditViewModel.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/timer/learning/LearningRecordWriteViewModel.kt
Labels: 🔨Fix, 🚨Bug

#207 익명 투표의 결과를 못보던 버그 수정
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/list/vote/component/OptionButton.kt
Labels: 🔨Fix, 🎨UI

#208 태그별 학습 시간 표현 로직 수정
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/record/RecordScreen.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/ui/theme/Type.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/util/CustomDateTimeFormatter.kt
Labels: 🎨UI

#217 스터디 관련 조회 커서 response값 수정
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkStudyGroupDataSource.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkStudyGroupDataSourceImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/mapper/cursor/CursorMapper.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/mapper/studies/StudiesMapper.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/cursor/NextCursorData.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/studies/response/CursorSliceStudiesListResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/studygroup/response/MyStudyGroupListResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/paging/MyStudyGroupListPagingSource.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/remote/StudyGroupApi.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/repository/StudiesRepositoryImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/cursor/NextCursorDomain.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studies/CursorStudiesPage.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studygroup/MyStudyGroupCursorSliceKey.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/find/StudiesFindContract.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/find/StudiesFindViewModel.kt
Labels: 💪Refactor

#218 그룹 탈퇴 API 연동
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkStudyGroupDataSource.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkStudyGroupDataSourceImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/remote/StudyGroupApi.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/repository/StudyGroupRepositoryImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/repository/StudyGroupRepository.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/usecase/studygroup/LeaveStudyGroupUseCase.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/drawer/DeleteStudiesDialog.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/component/drawer/StudiesDrawer.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/StudiesDetailContract.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/StudiesDetailViewModel.kt
Labels: 💡Feature, 🎨UI

#226 커서기반 페이징 조회 reposen, request 변경 (스터디 관련)
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkStudiesDataSource.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkStudiesDataSourceImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkStudyGroupDataSourceImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/mapper/studies/StudiesApplicationsMapper.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/mapper/studies/StudiesFeedsMapper.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/mapper/studies/StudiesWeeklyRankingsMapper.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/studies/response/GetStudiesApplicationsMembersResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/studies/response/GetStudiesFeedsResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/studies/response/GetStudiesWeeklyRankingsResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/studygroup/response/MemberWeeklyStudyContentBySliceResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/paging/MemberStudyContentsPagingSource.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/remote/StudiesApi.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/remote/StudyGroupApi.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/repository/StudiesRepositoryImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studies/CursorStudiesApplications.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studies/CursorStudiesFeeds.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studies/CursorStudiesWeeklyRankings.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studygroup/CursorSliceKey.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studygroup/MemberStudyContentCursorSliceKey.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studygroup/MemberStudyContentsRequest.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/repository/StudiesRepository.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/usecase/studies/GetStudiesFeedsUseCase.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/usecase/studies/GetStudiesWeeklyRankingsUseCase.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/StudiesDetailContract.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/detail/StudiesDetailViewModel.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/join/StudiesWaitingToJoinViewModel.kt
Labels: 💪Refactor

#229 투표 API 관련 Response 수정 및 마이그레이션
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkStudyGroupDataSourceImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/local/database/NeeGongNaeGongDatabase.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/local/database/entity/StudyGroupVoteHistoryRemoteKey.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/local/database/migration/MigrationFrom4To5.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/local/database/module/DBModule.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/studygroup/response/StudyGroupVoteListBySliceResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/paging/StudyGroupVoteHistoryRemoteMediator.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/remote/StudyGroupApi.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/model/studygroup/StudyGroupVoteListRequest.kt
Labels: 💪Refactor, 🚨Bug

#230 개인 공부기록 조회 공통커서 적용
  app/src/main/java/com/ssafy/neegongnaegong/data/datasource/network/NetworkLearningRecordDataSourceImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/learningrecord/request/GetLearningRecordListRequest.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/model/learningrecord/response/CursorSliceResponse.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/remote/LearningRecordApi.kt
  app/src/main/java/com/ssafy/neegongnaegong/data/repository/LearningRecordRepositoryImpl.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/repository/LearningRecordRepository.kt
  app/src/main/java/com/ssafy/neegongnaegong/domain/usecase/learningrecord/GetLearningRecordListUseCase.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/personal/PersonalContract.kt
  app/src/main/java/com/ssafy/neegongnaegong/presentation/personal/PersonalViewModel.kt
Labels: 💪Refactor

#232 fix(#231): 투표 생성 화면 뒤로가기 버그 수정
  app/schemas/com.ssafy.neegongnaegong.data.local.database.NeeGongNaeGongDatabase/5.json
  app/src/main/java/com/ssafy/neegongnaegong/presentation/group/vote/VoteViewModel.kt
Labels: 🎨UI, 🚨Bug
